### ISSUE TITLE
How to fill paragraph for the correct alignment?

### ISSUE THREAD

**Issue by avyukt** [sb2nov/resume#5]
Hi Sourabh, 

Great to use this template for CV. One query. When the description runs in two or more lines, there is an issue of the unfilled paragraph. The lines do not all end at the same point. 

I tried using \setspace and parskip but they don't solve the problem and stretch the CV to two pages as well.  Would you have any solution for this? 

Thanking you, 
Best, 
Anusha

```
% %%% * Correct indentation and line spacing
% % indentation and underfull, overfull boxes
%\usepackage[stretch=10]{microtype}
%\setlength{\parskip}{1.2ex}
 \usepackage[parfill]{parskip}
 \setlength{\parindent}{0em}
% \clubpenalty = 4000
% \widowpenalty = 4000
```

**Comment by rajesh-bachu** [comment]
I'd like to have 3 positions below organisation name and resume item to be same below Organization.
Can you suggest how to do that?

**Comment by sb2nov** [comment]
Should be fixed using https://github.com/sb2nov/resume/blob/master/sourabh_bajaj_resume.tex#L115
