### ISSUE TITLE
Link highlight

### ISSUE THREAD

**Issue by rayedbar** [sb2nov/resume#6]
I can't seem to figure why the header links are being highlighted. Cheers and tremendous work!
![link_highlight](https://user-images.githubusercontent.com/4649183/40266669-6b8fc5ec-5b71-11e8-8581-f60acd4f68a8.png)

**Comment by sb2nov** [comment]
Does this happen when you render the pdf or only in your latex editor?

**Comment by sb2nov** [comment]
Does this happen when you render the pdf or only in your latex editor?

**Comment by Sudha247** [comment]
`\usepackage[hidelinks]{hyperref}` instead of `\usepackage[pdftext]{hyperref}` will fix this.

**Comment by sb2nov** [comment]
Thanks @Sudha247. Fixed it in 98dd712

**Comment by rayedbar** [comment]
@sb2nov It used to show up on the rendered pdf.
@Sudha247 That is solution that I implemented after making this post

@sb2nov you replied a day after my post. I am sorry for not following up. Cheers
