### ISSUE TITLE
Align bullet points with bold text in 

### ISSUE THREAD

**Issue by singhsimranjot** [sb2nov/resume#7]
Instead of appearing in line with first line of resumeSubheading, the bullet point appear in middle of multiple lines in resumeSubheading. Can this be fixed?
![untitled](https://user-images.githubusercontent.com/5345430/41393056-fc641456-6f71-11e8-99bd-125c02b56112.png)

**Comment by sb2nov** [comment]
Should be possible. Feel free to send a PR if you want otherwise I'll take a look whenever I get some free time.
